title: M31 — Andromeda Galaxy
date: 2026-04-12
description: 100kly wide. distance 2.5Mly and closing
tags: [nebula, m31]
images:
  - file: ./M31 - Andromeda Galaxy.jpg
    alt: M31 - Andromeda Galaxy
    caption: RGB
    tags: [4k, wallpaper]
