title: Four Guardians
date: 2026-06-06
description: Gastonne, Gépardinne, Erwinne and the mighty Pedro the Little Bucket.
tags: [four-guardians, cats]
images:
  - file: ./four-guardians.webp 
    alt: Four Guardians
    caption: Four Guardians
    tags: [four-guardians]
  - file: ./gastonne.jpg 
    alt: Gastonne
    caption: Gastonne
    tags: [gastonne]
  - file: ./gepardinne.jpg 
    alt: Gépardinne
    caption: Gépardinne
    tags: [gepardninne]
  - file: ./erwinne.jpg
    alt: Erwinne
    caption: Erwinne
    tags: [erwinne]
  - file: ./pedro.jpg 
    alt: Pedro
    caption: Pedro the Little Bucket
    tags: [pedro]
  - file: ./zofka-la-palma.jpg
    alt: Soffie
    caption: The fifth guardian, Soffie, guarding the Gran Telescopio Canarias.
    tags: [žofka, soffie]
