title: M16 - Eagle Nebula
date: 2026-04-12
description: No green up there? - so what :)
tags: [nebula, m16, eagle nebula]
images:
  - file: ./M16 - Eagle Nebula.jpg
    alt: M16 - Eagle Nebula
    caption: M16 - Eagle Nebula
    tags: [4k, wallpaper]
  - file: ./pillars-of-creation-hubble.png
    alt: M42 - Orion Nebula
    caption: Hubble of Craetion - Hubble
    tags: [hubble]
  - file: ./pillars-of-creation-backyard.jpg
    alt: M42 - Orion Nebula
    caption: Hubble of Creation - backyard
    tags: []
