title: M16 - Eagle Nebula
date: 2025-06-22
description: no green up there? - so what
tags: [nebula, m16, eagle nebula, pillars of creation]
images:
  - file: ./M16 - Eagle Nebula.jpg
    alt: M16 - Eagle Nebula
    caption: M16 - Eagle Nebula
    tags: [4k, wallpaper, home-page]
    notes: >
      Astro community tends to dislike green since there is almost none of it in the universe, after all. The culprits are black body radiation curve and the stars themselves. 
      Even though most stars peak around green, they are intense also in blue and red. And that is white to us.
  - file: ./pillars-of-creation-hubble.png
    alt: Pillars of Craetion - Hubble
    caption: Pillars of Craetion - Hubble
    tags: [hubble]
  - file: ./pillars-of-creation-backyard.jpg
    alt: Pillars of Creation - backyard
    caption: Pillars of Creation - backyard
    tags: []
object:
  position: "RA 18h 18m 45s · Dec −13° 47′ 13\""
  culmination: "Late July"
  distance: "≈ 5700 ly"
  size: "≈ 70 ly across"
  apparentSize: "70 arcmin"
  constellation: "Serpens"