title: M16 - Eagle Nebula
name: M16
date: 2025-06-22
description: no green up there? - so what
tags: [nebula, m16, eagle nebula, pillars of creation]
images:
  - file: ./m16-eagle-nebula.jpg
    alt: M16 - Eagle Nebula
    caption: Autumnal melancholy on burning voids.
    tags: [4k, wallpaper, home-page]
    notes: |
      The astro community tends to dislike green since there is almost none of it in the universe, after all.
      The culprits are the black body radiation curve and the stars themselves. Even though lots of stars peak around green, they are intense also in blue and red.

      And that is white to us.

      <a href="/astro/blog/2026-05-12-a-fear-and-loathing-of-green/">A Fear and Loathing of Green →</a>
  - file: ./pillars-of-creation-hubble.png
    alt: Pillars of Creation - Hubble
    caption: Pillars of Creation - Hubble
    tags: [hubble]
  - file: ./pillars-of-creation-backyard.jpg
    alt: Pillars of Creation - backyard
    caption: Pillars of Creation - backyard
    tags: []
object:
  position: "RA 18h 18m 45s · Dec −13° 47′ 13\""
  culmination: "Late July"
  distance: "≈ 5700 ly"
  size: "≈ 70 ly across"
  apparentSize: "70 arcmin"
  constellation: "Serpens"