title: M42 — Orion Nebula
date: 2024-01-10
description: 100kly wide. distance 2.5Mly and closing
tags: [nebula, m42, ngc1976, sh2-279]
images:
  - file: ./M42 - Orion Nebula.jpg
    alt: M42 - Orion Nebula
    caption: RGB
    tags: [4k, wallpaper, home-page]
  - file: ./M42 - lomo1.jpg
    alt: M42 - Orion Nebula
    caption: First take at astrohoto
    tags: [lomo]
  - file: ./M42 - lomo2.jpg
    alt: M42 - Orion Nebula
    caption: Second Take
    tags: [lomo]
object:
  position: "RA 5h 35m 17s · Dec −5° 23′ 15\""
  culmination: "Late January"
  distance: "≈ 1344 ly"
  size: "≈ 24 ly across"
  apparentSize: "65′ × 60′"
  constellation: Orion
