title: NGC4070
date: 2026-04-12
description: A
tags: [nebula, NGC4070]
images:
  - file: ./NGC4070.jpg
    alt: NGC4070
    caption: RGB
    tags: [4k, wallpaper, home-page]
object:
  position: "RA 12h 04m 12s · Dec +20° 24′"
  culmination: "Mid-April"
