title: Gran Telescopio Canarias
date: 2024-10-27
description: >-
  Inside the Gran Telescopio Canarias - 10.4 m
cover: ./PXL_20241027_115742023.MP.jpg
tags: [la-palma, roque-de-los-muchachos, gtc, gran-telescopio-canarias, telescope, astronomy, pilgrimage]
images:
  - file: ./PXL_20241027_092941406.MP.jpg
    sizes: [800]
    caption: Arrival in the cloud

  - file: ./PXL_20241027_114229777.jpg
    sizes: [800]
    caption: A little Alt-Az Mount with a friend :)

  - file: ./PXL_20241027_114332768.jpg
    sizes: [800]

  - file: ./PXL_20241027_114422118.jpg
    sizes: [800]
    caption: The secondary mirror

  - file: ./PXL_20241027_114615842.jpg
    sizes: [800]
    caption: Instrument selection mirror

  - file: ./PXL_20241027_114620806.jpg
    sizes: [800]

  - file: ./PXL_20241027_114802441.jpg
    sizes: [800]
    caption: Dirty little mirrors

  - file: ./PXL_20241027_114810661.jpg
    sizes: [800]

  - file: ./PXL_20241027_114827566.MP.jpg
    sizes: [800]
    caption: The secondary mirror

  - file: ./PXL_20241027_114833541.jpg
    sizes: [800]

  - file: ./PXL_20241027_115431250.MP.jpg
    sizes: [800]
    caption: Another view at the secondary mirror assembly.

  - file: ./PXL_20241027_115742023.MP.jpg
    sizes: [800]
    caption: The primary mirror back side

  - file: ./PXL_20241027_120048186.jpg
    sizes: [800]

  - file: ./PXL_20241027_120252354.MP.jpg
    sizes: [800]

  - file: ./PXL_20241027_122240363.jpg
    sizes: [800]

  - file: ./PXL_20241027_124738746.jpg
    sizes: [800]
